Fri Dec 17 03:58:29 2021

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/disnake/client.py", line 515, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 255, in on_slash_command_error
    dict_args = await base_on_error(inter, error)
  File "/home/runner/TheDiscordMathProblemBot/helpful_modules/threads_or_useful_funcs.py", line 41, in base_on_error
    "\n".join(traceback.format_exception(error)),  # python 3.10 only!
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'


